import type { CityName, ValuationRequest } from '@/types/api.types'

export const CITY_NAMES: CityName[] = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Pune',
  'Chennai',
  'Kolkata',
  'Ahmedabad',
]

export const CITY_INFO: Record<
  CityName,
  { tier: number; base_psf: number; population_m: number }
> = {
  Mumbai: { tier: 1, base_psf: 18500, population_m: 20.4 },
  Delhi: { tier: 1, base_psf: 9500, population_m: 18.9 },
  Bangalore: { tier: 1, base_psf: 7500, population_m: 12.3 },
  Hyderabad: { tier: 2, base_psf: 6200, population_m: 10.0 },
  Pune: { tier: 2, base_psf: 6800, population_m: 6.4 },
  Chennai: { tier: 2, base_psf: 5800, population_m: 10.9 },
  Kolkata: { tier: 2, base_psf: 4200, population_m: 14.9 },
  Ahmedabad: { tier: 2, base_psf: 4800, population_m: 8.4 },
}

export const DEMO_PROPERTY: ValuationRequest = {
  city: 'Mumbai',
  zone: 'Western Suburbs',
  locality: 'Bandra',
  property_type: 'Apartment',
  sub_type: '3BHK',
  area_sqft: 1200,
  age_years: 5,
  floor_number: 15,
  total_floors: 28,
  bedrooms: 3,
  bathrooms: 3,
  parking_slots: 2,
  furnishing: 1,
  occupancy: 0,
  monthly_rent: 0,
  ownership_type: 'Freehold',
  lift_available: true,
  security_available: true,
  gym_available: true,
  swimming_pool: true,
  clubhouse: true,
  power_backup: true,
  intercom: true,
  cctv: true,
  rera_registered: true,
  oc_received: true,
  cc_received: true,
  bmc_approved: true,
  legal_clear: true,
  encumbrance_flag: false,
  litigation_flag: false,
  title_age_years: 5,
  registered_sale_deed: true,
  loan_on_property: false,
  mutation_done: true,
  flood_zone_flag: false,
  crz_flag: false,
  heritage_zone_flag: false,
  slum_proximity_flag: false,
  planned_zone_flag: true,
  it_park_proximity: false,
  img_count: 8,
  vastu_compliant: true,
  corner_unit: false,
  east_facing: true,
  balcony_count: 2,
  servant_room: false,
  modular_kitchen: true,
  smart_home: false,
}

export const DEFAULT_FORM_PROPERTY: ValuationRequest = {
  ...DEMO_PROPERTY,
  city: 'Mumbai',
  zone: '',
  locality: '',
  sub_type: '2BHK',
  area_sqft: 700,
  age_years: 8,
  floor_number: 3,
  total_floors: 12,
  bedrooms: 2,
  bathrooms: 2,
  parking_slots: 1,
  furnishing: 1,
  occupancy: 0,
  monthly_rent: 0,
  gym_available: false,
  swimming_pool: false,
  clubhouse: false,
  img_count: 3,
  balcony_count: 1,
}

export const FRAUD_FLAG_LABELS: Record<string, string> = {
  R01: 'Overvaluation detected',
  R02: 'Undervaluation detected',
  R03: 'Cap rate anomaly',
  R04: 'Area out of bounds',
  R05: 'Age inconsistency',
  R06: 'Floor inconsistency',
  R07: 'Listing vs circle rate mismatch',
  R08: 'Title risk',
  R09: 'Below circle rate threshold',
  R10: 'Rental yield anomaly',
}
